/* Compare materialized bridge AdaLN vectors with the original schedule path
 * evaluated at the same effective timesteps. Uses released weights, no fixture
 * generated by the implementation under test. */
#include "src/denoise/dit_schedule.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CHECK(x) do { if (!(x)) { fprintf(stderr,"FAIL %s:%d: %s (%s)\n",__FILE__,__LINE__,#x,error); exit(1); } } while (0)
enum { BLOCK_WIDTH=3*6*5376, FINAL_WIDTH=2*5376 };
static float f32(uint16_t value) {
    uint32_t bits=(uint32_t)value<<16; float result; memcpy(&result,&bits,4); return result;
}

int main(int argc,char **argv) {
    char error[512]={0},path[4096];
    snprintf(path,sizeof(path),"%s/Ref2VA/transformer",argc>1?argv[1]:"models/MiniMax-H3");
    h3_weight_store *weights=h3_weight_store_open(path,error,sizeof(error)); CHECK(weights);
    h3_gpu *gpu=h3_gpu_create("src/metal/shaders.metal",error,sizeof(error)); CHECK(gpu);
    h3_bridge_profile p; CHECK(h3_bridge_profile_build(39,8,.5f,H3_BRIDGE_STEPPED,&p,NULL,0,error,sizeof(error)));
    h3_sigma_schedule sigmas={0}; sigmas.steps=3;
    sigmas.video[0]=sigmas.audio[0]=1;
    sigmas.video[1]=.7f; sigmas.audio[1]=.4f;
    sigmas.video[2]=.0001f; sigmas.audio[2]=.00001f;
    h3_sigma_schedule reference={0};
    int reference_step[3][H3_TARGET_ROW_CLASSES];
    for (int step=0;step<3;step++) for (int c=0;c<H3_TARGET_ROW_CLASSES;c++) {
        reference_step[step][c]=-1;
        if (!p.active[c]) continue;
        float time=h3_bridge_class_timestep(&p,(h3_target_row_class)c,sigmas.video[step],sigmas.audio[step]);
        int index=reference.steps++;
        reference_step[step][c]=index;
        reference.video[index]=reference.audio[index]=1-time;
        CHECK(1-reference.video[index]==time);
    }
    h3_dit_schedule *bridge=h3_dit_schedule_precompute_bridge(weights,gpu,&sigmas,&p,NULL,NULL,error,sizeof(error)); CHECK(bridge);
    h3_dit_schedule *plain=h3_dit_schedule_precompute(weights,gpu,&reference,1,1,NULL,NULL,error,sizeof(error)); CHECK(plain);
    size_t br=h3_dit_schedule_time_rows(bridge), pr=h3_dit_schedule_time_rows(plain);
    uint16_t *actual=malloc(br*BLOCK_WIDTH*2), *expected=malloc(pr*BLOCK_WIDTH*2); CHECK(actual && expected);
    double max_relative=0,max_l2=0;
    size_t vectors=0;
    for (int block=0;block<=50;block++) {
        size_t width=block==50?FINAL_WIDTH:BLOCK_WIDTH;
        const h3_gpu_tensor *b=block==50?h3_dit_schedule_final(bridge):h3_dit_schedule_block(bridge,(unsigned)block);
        const h3_gpu_tensor *r=block==50?h3_dit_schedule_final(plain):h3_dit_schedule_block(plain,(unsigned)block);
        CHECK(h3_gpu_tensor_read_bf16(b,actual,br*width));
        CHECK(h3_gpu_tensor_read_bf16(r,expected,pr*width));
        for (int step=0;step<3;step++) for (int c=0;c<H3_TARGET_ROW_CLASSES;c++) if (p.active[c]) {
            uint32_t bi=h3_dit_schedule_class_row(bridge,step,(h3_target_row_class)c);
            uint32_t ri=h3_dit_schedule_video_row(plain,reference_step[step][c]);
            CHECK(bi<br && ri<pr);
            double difference=0,maximum=0,sq=0,norm=0;
            for (size_t i=0;i<width;i++) {
                double x=f32(actual[(size_t)bi*width+i]), y=f32(expected[(size_t)ri*width+i]);
                CHECK(isfinite(x) && isfinite(y));
                difference=fmax(difference,fabs(x-y)); maximum=fmax(maximum,fabs(y));
                sq+=(x-y)*(x-y); norm+=y*y;
            }
            double relative=difference/fmax(maximum,1e-12), l2=sqrt(sq/fmax(norm,1e-24));
            CHECK(relative<.025 && l2<.025); /* Existing released AdaLN parity bounds. */
            max_relative=fmax(max_relative,relative); max_l2=fmax(max_l2,l2); vectors++;
        }
    }
    printf("ok: %zu materialized bridge modulation vectors across all 50 blocks and final heads; rel-max %.9g, rel-L2 %.9g\n",vectors,max_relative,max_l2);
    free(actual); free(expected); h3_dit_schedule_free(bridge); h3_dit_schedule_free(plain);
    h3_gpu_free(gpu); h3_weight_store_free(weights);
    return 0;
}
