/* Generated by scripts/cuda_translate_reference.py; edit the generator or
 * authoritative portable Metal kernel, then regenerate. CUDA-specific
 * execution/attention/GEMM remains in separately maintained sources. */

using uint = unsigned int;
using ushort = unsigned short;

__device__ inline float h3_bf16_to_f32(ushort v) { return __uint_as_float(uint(v)<<16); }

__device__ inline ushort h3_f32_to_bf16(float v) { uint b=__float_as_uint(v); return ushort((b+0x7fff+((b>>16)&1))>>16); }

template<class T> __device__ T clamp(T v,T lo,T hi) { return min(hi,max(lo,v)); }

struct linear_args {
    uint rows;
    uint input_dim;
    uint output_dim;
    uint has_bias;
};

struct norm_args {
    uint rows;
    uint width;
    float epsilon;
};

struct qkv_args {
    uint sequence;
    uint heads;
    uint head_dim;
    uint rope_half;
    uint grouped;
    float epsilon;
};

struct scale_add_args { uint rows; uint width; };

struct adaln_args {
    uint rows;
    uint width;
    uint slots;
    uint shift_slot;
    uint scale_slot;
    float epsilon;
};

struct gate_args {
    uint rows;
    uint width;
    uint slots;
    uint gate_slot;
};

struct swiglu_args {
    uint rows;
    uint width;
};

struct vae_encoder_pad_args {
    uint batch;
    uint depth;
    uint height;
    uint width;
    uint channels;
    uint depth_front;
    uint height_before;
    uint height_after;
    uint width_before;
    uint width_after;
};

struct vae_encoder_norm_args {
    uint batch;
    uint depth;
    uint height;
    uint width;
    uint channels;
    uint groups;
    float epsilon;
};

struct weight_norm_args {
    uint outer;
    uint inner;
};

struct add_scaled_args {
    uint elements;
    float left_scale;
    float right_scale;
};

struct audio_activation_args {
    uint batch;
    uint length;
    uint channels;
};

struct audio_qkv_args {
    uint batch;
    uint length;
    uint heads;
    uint head_dim;
};

struct audio_pool_args {
    uint batch;
    uint length;
    uint heads;
    uint head_dim;
    uint output_dim;
};

struct clip_args {
    uint elements;
    float minimum;
    float maximum;
};

struct gelu_bf16_args {
    uint elements;
    uint approximate;
};

struct embedding_args {
    uint tokens;
    uint vocab_size;
    uint width;
};

struct text_rope_args {
    uint sequence;
    uint query_heads;
    uint kv_heads;
    uint head_dim;
    float epsilon;
};

struct head_norm_args {
    uint sequence;
    uint heads;
    uint head_dim;
    float epsilon;
};

struct text_rope_inplace_args {
    uint sequence;
    uint query_heads;
    uint kv_heads;
    uint head_dim;
};

struct h3_token_pool_args {
    uint input_offset;
    uint original_offset;
    uint baseline_offset;
    uint rows;
    uint width;
};

struct h3_token_expand_args {
    uint original_offset;
    uint baseline_offset;
    uint rows;
    uint width;
    uint exact_prefix_rows;
    float update_scale;
};

struct h3_euler_args {
    uint sample_offset;
    uint elements;
    float delta;
    float ratio;
};

struct h3_bridge_euler_args {
    uint sample_offset;
    uint elements;
    uint row_width;
    uint classes;
    float delta;
    float ratio;
};

struct h3_video_preview_args {
    uint offset, elements, time, height, width, masked, classes;
    float sigma, ratio;
};

__device__ static int h3_reflect_coordinate(int coordinate, int length) {
    if (coordinate < 0) return -coordinate;
    if (coordinate >= length) return 2 * length - coordinate - 2;
    return coordinate;
}

__device__ inline float h3_erf_approx(float value) {
    float sign = value < 0.0f ? -1.0f : 1.0f;
    float x = abs(value);
    float t = 1.0f / (1.0f + 0.3275911f * x);
    float polynomial = (((((1.061405429f * t - 1.453152027f) * t) +
                           1.421413741f) * t - 0.284496736f) * t +
                           0.254829592f) * t;
    return sign * (1.0f - polynomial * expf(-x * x));
}

__global__ void h3_linear_f32_tiled(const float *input, const float *weight, const float *bias, float *output, linear_args args) {
    uint2 tid = make_uint2(threadIdx.x,threadIdx.y);
    uint2 group = make_uint2(blockIdx.x,blockIdx.y);

    __shared__ float input_tile[16][16];
    __shared__ float weight_tile[16][16];
    uint row = group.y * 16 + tid.y;
    uint column = group.x * 16 + tid.x;
    float sum = args.has_bias && column < args.output_dim ?
        bias[column] : 0.0f;
    uint tile_count = (args.input_dim + 15) / 16;
    for (uint tile = 0; tile < tile_count; tile++) {
        uint input_k = tile * 16 + tid.x;
        input_tile[tid.y][tid.x] =
            row < args.rows && input_k < args.input_dim ?
            input[row * args.input_dim + input_k] : 0.0f;
        uint weight_k = tile * 16 + tid.y;
        weight_tile[tid.y][tid.x] =
            column < args.output_dim && weight_k < args.input_dim ?
            weight[column * args.input_dim + weight_k] : 0.0f;
        __syncthreads();
        for (uint k = 0; k < 16; k++)
            sum = fmaf(input_tile[tid.y][k], weight_tile[k][tid.x], sum);
        __syncthreads();
    }
    if (row < args.rows && column < args.output_dim)
        output[row * args.output_dim + column] = sum;

}

__global__ void h3_linear_f32_tiled_bf16(const float *input, const float *weight, const float *bias, ushort *output, linear_args args) {
    uint2 tid = make_uint2(threadIdx.x,threadIdx.y);
    uint2 group = make_uint2(blockIdx.x,blockIdx.y);

    __shared__ float input_tile[16][16];
    __shared__ float weight_tile[16][16];
    uint row = group.y * 16 + tid.y;
    uint column = group.x * 16 + tid.x;
    float sum = args.has_bias && column < args.output_dim ?
        bias[column] : 0.0f;
    uint tile_count = (args.input_dim + 15) / 16;
    for (uint tile = 0; tile < tile_count; tile++) {
        uint input_k = tile * 16 + tid.x;
        input_tile[tid.y][tid.x] =
            row < args.rows && input_k < args.input_dim ?
            input[row * args.input_dim + input_k] : 0.0f;
        uint weight_k = tile * 16 + tid.y;
        weight_tile[tid.y][tid.x] =
            column < args.output_dim && weight_k < args.input_dim ?
            weight[column * args.input_dim + weight_k] : 0.0f;
        __syncthreads();
        for (uint k = 0; k < 16; k++)
            sum = fmaf(input_tile[tid.y][k], weight_tile[k][tid.x], sum);
        __syncthreads();
    }
    if (row < args.rows && column < args.output_dim)
        output[row * args.output_dim + column] = h3_f32_to_bf16(sum);

}

__global__ void h3_linear_f32_tiled_bf16_map(const float *input, const float *weight, const float *bias, ushort *output, linear_args args, const uint *row_map) {
    uint2 tid = make_uint2(threadIdx.x,threadIdx.y);
    uint2 group = make_uint2(blockIdx.x,blockIdx.y);

    __shared__ float input_tile[16][16];
    __shared__ float weight_tile[16][16];
    __shared__ uint output_rows[16];
    uint row = group.y * 16 + tid.y;
    uint column = group.x * 16 + tid.x;
    if (tid.x == 0)
        output_rows[tid.y] = row < args.rows ? row_map[row] : 0;
    __syncthreads();
    float sum = args.has_bias && column < args.output_dim ?
        bias[column] : 0.0f;
    uint tile_count = (args.input_dim + 15) / 16;
    for (uint tile = 0; tile < tile_count; tile++) {
        uint input_k = tile * 16 + tid.x;
        input_tile[tid.y][tid.x] =
            row < args.rows && input_k < args.input_dim ?
            input[row * args.input_dim + input_k] : 0.0f;
        uint weight_k = tile * 16 + tid.y;
        weight_tile[tid.y][tid.x] =
            column < args.output_dim && weight_k < args.input_dim ?
            weight[column * args.input_dim + weight_k] : 0.0f;
        __syncthreads();
        for (uint k = 0; k < 16; k++)
            sum = fmaf(input_tile[tid.y][k], weight_tile[k][tid.x], sum);
        __syncthreads();
    }
    if (row < args.rows && column < args.output_dim)
        output[output_rows[tid.y] * args.output_dim + column] =
            h3_f32_to_bf16(sum);

}

__global__ void h3_silu_f32(const float *input, float *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= count) return;
    float value = input[gid];
    output[gid] = value / (1.0f + expf(-value));

}

__global__ void h3_cast_f32_to_bf16(const float *input, ushort *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid < count) output[gid] = h3_f32_to_bf16(input[gid]);

}

__global__ void h3_cast_bf16_to_f32(const ushort *input, float *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid < count) output[gid] = h3_bf16_to_f32(input[gid]);

}

__global__ void h3_rms_norm_f32(const float *input, const float *weight, float *output, norm_args args) {
    uint3 group = make_uint3(blockIdx.x,blockIdx.y,blockIdx.z);
    uint3 thread_position = make_uint3(threadIdx.x,threadIdx.y,threadIdx.z);
    uint3 threadgroup_size = make_uint3(blockDim.x,blockDim.y,blockDim.z);

    uint row = group.x;
    uint tid = thread_position.x;
    uint threads = threadgroup_size.x;
    if (row >= args.rows) return;
    __shared__ float reductions[256];
    const float *x = input + row * args.width;
    float local_sum = 0.0f;
    for (uint k = tid; k < args.width; k += threads)
        local_sum = fmaf(x[k], x[k], local_sum);
    reductions[tid] = local_sum;
    __syncthreads();
    for (uint stride = threads / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float inverse = rsqrtf(reductions[0] / float(args.width) + args.epsilon);
    for (uint column = tid; column < args.width; column += threads)
        output[row * args.width + column] = x[column] * inverse * weight[column];

}

__global__ void h3_scale_add_f32(const float *residual, const float *branch, const float *scale, float *output, scale_add_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    uint index = row * args.width + column;
    output[index] = residual[index] + branch[index] * scale[column];

}

__global__ void h3_layer_norm_f32(const float *input, const float *weight, const float *bias, float *output, norm_args args) {
    uint3 group = make_uint3(blockIdx.x,blockIdx.y,blockIdx.z);
    uint3 thread_position = make_uint3(threadIdx.x,threadIdx.y,threadIdx.z);
    uint3 threadgroup_size = make_uint3(blockDim.x,blockDim.y,blockDim.z);

    uint row = group.x;
    uint tid = thread_position.x;
    uint threads = threadgroup_size.x;
    if (row >= args.rows) return;
    __shared__ float reductions[256];
    const float *x = input + row * args.width;
    float local = 0.0f;
    for (uint k = tid; k < args.width; k += threads) local += x[k];
    reductions[tid] = local;
    __syncthreads();
    for (uint stride = threads / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float mean = reductions[0] / float(args.width);
    __syncthreads();
    local = 0.0f;
    for (uint k = tid; k < args.width; k += threads) {
        float centered = x[k] - mean;
        local = fmaf(centered, centered, local);
    }
    reductions[tid] = local;
    __syncthreads();
    for (uint stride = threads / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float inverse = rsqrtf(reductions[0] / float(args.width) + args.epsilon);
    for (uint column = tid; column < args.width; column += threads)
        output[row * args.width + column] =
            (x[column] - mean) * inverse * weight[column] + bias[column];

}

__global__ void h3_video_qkv_rope_f32(const float *qkv, const float *rope_cos, const float *rope_sin, float *query, float *key, float *value, qkv_args args) {
    uint3 gid = make_uint3((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y),(blockIdx.z*blockDim.z+threadIdx.z));

    uint dimension = gid.x;
    uint head = gid.y;
    uint row = gid.z;
    if (dimension >= args.head_dim || head >= args.heads || row >= args.sequence) return;
    uint base = (row * args.heads + head) * args.head_dim * 3;
    float q_sum = 0.0f, k_sum = 0.0f;
    for (uint d = 0; d < args.head_dim; d++) {
        float q = qkv[base + d];
        float k = qkv[base + args.head_dim + d];
        q_sum = fmaf(q, q, q_sum);
        k_sum = fmaf(k, k, k_sum);
    }
    float qi = rsqrtf(q_sum / float(args.head_dim) + args.epsilon);
    float ki = rsqrtf(k_sum / float(args.head_dim) + args.epsilon);
    float q0 = qkv[base + dimension] * qi;
    float k0 = qkv[base + args.head_dim + dimension] * ki;
    if (dimension < args.rope_half) {
        uint pair = dimension + args.rope_half;
        float q1 = qkv[base + pair] * qi;
        float k1 = qkv[base + args.head_dim + pair] * ki;
        float c = rope_cos[row * args.rope_half + dimension];
        float s = rope_sin[row * args.rope_half + dimension];
        q0 = q0 * c - q1 * s;
        k0 = k0 * c - k1 * s;
    } else if (dimension < args.rope_half * 2) {
        uint pair = dimension - args.rope_half;
        float q1 = qkv[base + pair] * qi;
        float k1 = qkv[base + args.head_dim + pair] * ki;
        float c = rope_cos[row * args.rope_half + pair];
        float s = rope_sin[row * args.rope_half + pair];
        q0 = q0 * c + q1 * s;
        k0 = k0 * c + k1 * s;
    }
    uint output_index = (row * args.heads + head) * args.head_dim + dimension;
    query[output_index] = q0;
    key[output_index] = k0;
    value[output_index] = qkv[base + args.head_dim * 2 + dimension];

}

__global__ void h3_adaln_f32(const float *input, const float *weight, const float *modulation, const uint *row_map, float *output, adaln_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    const float *x = input + row * args.width;
    float sum = 0.0f;
    for (uint k = 0; k < args.width; k++) sum = fmaf(x[k], x[k], sum);
    float normalized = x[column] * rsqrtf(sum / float(args.width) + args.epsilon) * weight[column];
    uint modulation_row = row_map[row];
    uint base = modulation_row * args.slots * args.width;
    float shift = modulation[base + args.shift_slot * args.width + column];
    float scale = modulation[base + args.scale_slot * args.width + column];
    output[row * args.width + column] = fmaf(normalized, (1.0f + scale), shift);

}

__global__ void h3_gate_f32(const float *residual, const float *branch, const float *modulation, const uint *row_map, float *output, gate_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    uint base = row_map[row] * args.slots * args.width;
    float gate = modulation[base + args.gate_slot * args.width + column];
    uint index = row * args.width + column;
    output[index] = residual[index] + branch[index] * gate;

}

__global__ void h3_qkv_rope_f32(const float *qkv, const float *q_weight, const float *k_weight, const float *rope_cos, const float *rope_sin, float *query, float *key, float *value, qkv_args args) {
    uint3 gid = make_uint3((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y),(blockIdx.z*blockDim.z+threadIdx.z));

    uint dimension = gid.x;
    uint head = gid.y;
    uint row = gid.z;
    if (dimension >= args.head_dim || head >= args.heads || row >= args.sequence) return;
    uint inner = args.heads * args.head_dim;
    uint row_base = row * inner * 3;
    uint q_base = row_base + head * args.head_dim;
    uint k_base = q_base + inner;
    uint v_base = q_base + inner * 2;
    if (args.grouped) {
        q_base = row_base + head * args.head_dim * 3;
        k_base = q_base + args.head_dim;
        v_base = k_base + args.head_dim;
    }
    float q_sum = 0.0f;
    float k_sum = 0.0f;
    for (uint d = 0; d < args.head_dim; d++) {
        float q = qkv[q_base + d];
        float k = qkv[k_base + d];
        q_sum = fmaf(q, q, q_sum);
        k_sum = fmaf(k, k, k_sum);
    }
    float q_inverse = rsqrtf(q_sum / float(args.head_dim) + args.epsilon);
    float k_inverse = rsqrtf(k_sum / float(args.head_dim) + args.epsilon);
    float q0 = qkv[q_base + dimension] * q_inverse * q_weight[dimension];
    float k0 = qkv[k_base + dimension] * k_inverse * k_weight[dimension];
    if (dimension < args.rope_half) {
        uint pair = dimension + args.rope_half;
        float q1 = qkv[q_base + pair] * q_inverse * q_weight[pair];
        float k1 = qkv[k_base + pair] * k_inverse * k_weight[pair];
        float c = rope_cos[row * args.rope_half + dimension];
        float s = rope_sin[row * args.rope_half + dimension];
        q0 = q0 * c - q1 * s;
        k0 = k0 * c - k1 * s;
    } else if (dimension < args.rope_half * 2) {
        uint pair = dimension - args.rope_half;
        float q1 = qkv[q_base + pair] * q_inverse * q_weight[pair];
        float k1 = qkv[k_base + pair] * k_inverse * k_weight[pair];
        float c = rope_cos[row * args.rope_half + pair];
        float s = rope_sin[row * args.rope_half + pair];
        q0 = q0 * c + q1 * s;
        k0 = k0 * c + k1 * s;
    }
    uint output_index = (row * args.heads + head) * args.head_dim + dimension;
    query[output_index] = q0;
    key[output_index] = k0;
    value[output_index] = qkv[v_base + dimension];

}

__global__ void h3_swiglu_f32(const float *fused, float *output, swiglu_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    uint base = row * args.width * 2;
    float gate = fused[base + column];
    float up = fused[base + args.width + column];
    output[row * args.width + column] = gate / (1.0f + expf(-gate)) * up;

}

__global__ void h3_vae_encoder_pad_f32(const float *input, float *output, vae_encoder_pad_args args) {
    uint3 gid = make_uint3((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y),(blockIdx.z*blockDim.z+threadIdx.z));

    uint channel = gid.x;
    uint out_x = gid.y;
    uint out_height = args.height + args.height_before + args.height_after;
    uint out_width = args.width + args.width_before + args.width_after;
    uint out_depth = args.depth + args.depth_front;
    uint plane = gid.z;
    if (channel >= args.channels || out_x >= out_width ||
        plane >= args.batch * out_depth * out_height) return;
    uint out_y = plane % out_height;
    uint temporal_plane = plane / out_height;
    uint out_t = temporal_plane % out_depth;
    uint batch = temporal_plane / out_depth;
    size_t destination = ((((size_t)batch * out_depth + out_t) * out_height +
                           out_y) * out_width + out_x) * args.channels +
                         channel;
    if (out_t < args.depth_front) {
        output[destination] = 0.0f;
        return;
    }
    int source_y = h3_reflect_coordinate(
        int(out_y) - int(args.height_before), int(args.height));
    int source_x = h3_reflect_coordinate(
        int(out_x) - int(args.width_before), int(args.width));
    uint source_t = out_t - args.depth_front;
    size_t source = ((((size_t)batch * args.depth + source_t) * args.height +
                      uint(source_y)) * args.width + uint(source_x)) *
                    args.channels + channel;
    output[destination] = input[source];

}

__global__ void h3_vae_encoder_group_norm_silu_f32(const float *input, const float *weight, const float *bias, float *output, vae_encoder_norm_args args) {
    uint3 group = make_uint3(blockIdx.x,blockIdx.y,blockIdx.z);
    uint3 thread_position = make_uint3(threadIdx.x,threadIdx.y,threadIdx.z);
    uint3 threadgroup_size = make_uint3(blockDim.x,blockDim.y,blockDim.z);

    uint row = group.x;
    uint tid = thread_position.x;
    uint rows = args.batch * args.depth * args.groups;
    if (row >= rows) return;
    uint channels_per_group = args.channels / args.groups;
    uint group_index = row % args.groups;
    uint temporal_plane = row / args.groups;
    uint elements = args.height * args.width * channels_per_group;
    __shared__ float reductions[256];
    float local = 0.0f;
    for (uint index = tid; index < elements; index += threadgroup_size.x) {
        uint spatial = index / channels_per_group;
        uint channel = group_index * channels_per_group +
                       index % channels_per_group;
        size_t source = ((size_t)temporal_plane * args.height * args.width +
                         spatial) * args.channels + channel;
        local += input[source];
    }
    reductions[tid] = local;
    __syncthreads();
    for (uint stride = threadgroup_size.x / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float mean = reductions[0] / float(elements);
    __syncthreads();
    local = 0.0f;
    for (uint index = tid; index < elements; index += threadgroup_size.x) {
        uint spatial = index / channels_per_group;
        uint channel = group_index * channels_per_group +
                       index % channels_per_group;
        size_t source = ((size_t)temporal_plane * args.height * args.width +
                         spatial) * args.channels + channel;
        float centered = input[source] - mean;
        local = fmaf(centered, centered, local);
    }
    reductions[tid] = local;
    __syncthreads();
    for (uint stride = threadgroup_size.x / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float inverse = rsqrtf(reductions[0] / float(elements) + args.epsilon);
    for (uint index = tid; index < elements; index += threadgroup_size.x) {
        uint spatial = index / channels_per_group;
        uint channel = group_index * channels_per_group +
                       index % channels_per_group;
        size_t destination =
            ((size_t)temporal_plane * args.height * args.width + spatial) *
            args.channels + channel;
        float value = (input[destination] - mean) * inverse * weight[channel] +
                      bias[channel];
        output[destination] = value / (1.0f + expf(-value));
    }

}

__global__ void h3_weight_norm_f32(const float *vector, const float *magnitude, float *output, weight_norm_args args) {
    uint row = (blockIdx.x*blockDim.x+threadIdx.x);

    if (row >= args.outer) return;
    uint base = row * args.inner;
    float square_sum = 0.0f;
    for (uint index = 0; index < args.inner; index++) {
        float value = vector[base + index];
        square_sum = fmaf(value, value, square_sum);
    }
    float scale = magnitude[row] * rsqrtf(square_sum);
    for (uint index = 0; index < args.inner; index++)
        output[base + index] = vector[base + index] * scale;

}

__global__ void h3_add_scaled_f32(const float *left, const float *right, float *output, add_scaled_args args) {
    uint index = (blockIdx.x*blockDim.x+threadIdx.x);

    if (index < args.elements)
        output[index] = left[index] * args.left_scale +
                        right[index] * args.right_scale;

}

__global__ void h3_alias_free_snake_f32(const float *input, const float *alpha_log, const float *beta_log, const float *upsample_filter, const float *downsample_filter, float *output, audio_activation_args args, uint time_base) {
    uint3 gid = make_uint3((blockIdx.x*blockDim.x+threadIdx.x),(time_base+blockIdx.y*blockDim.y+threadIdx.y),(blockIdx.z*blockDim.z+threadIdx.z));

    uint channel = gid.x;
    uint time = gid.y;
    uint batch = gid.z;
    if (channel >= args.channels || time >= args.length ||
        batch >= args.batch) return;
    float alpha = expf(alpha_log[channel]);
    float beta = expf(beta_log[channel]);
    float result = 0.0f;
    for (int down_k = 0; down_k < 12; down_k++) {
        int up_time = int(time * 2) + down_k - 5;
        up_time = clamp(up_time, 0, int(args.length * 2) - 1);
        int raw_time = up_time + 15;
        float upsampled = 0.0f;
        for (int up_k = 0; up_k < 12; up_k++) {
            int numerator = raw_time - up_k;
            if (numerator < 0 || (numerator & 1)) continue;
            int padded_time = numerator / 2;
            int source_time = clamp(padded_time - 5, 0,
                                    int(args.length) - 1);
            uint source = (batch * args.length + uint(source_time)) *
                          args.channels + channel;
            upsampled = fmaf(input[source], 2.0f * upsample_filter[up_k],
                            upsampled);
        }
        float sine = sinf(alpha * upsampled);
        float activated = upsampled + sine * sine / (beta + 1e-9f);
        result = fmaf(activated, downsample_filter[down_k], result);
    }
    uint destination = (batch * args.length + time) * args.channels + channel;
    output[destination] = result;

}

__global__ void h3_snake1d_f32(const float *input, const float *alpha, float *output, audio_activation_args args) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    uint count = args.batch * args.length * args.channels;
    if (gid >= count) return;
    float a = alpha[gid % args.channels];
    float x = input[gid];
    float wave = sinf(a * x);
    output[gid] = x + wave * wave / (a + 1e-9f);

}

__global__ void h3_audio_qkv_split_f32(const float *qkv, const float *q_bias, const float *k_bias, const float *v_bias, float *query, float *key, float *value, audio_qkv_args args) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    uint width = args.heads * args.head_dim;
    uint count = args.batch * args.length * width;
    if (gid >= count) return;
    uint column = gid % width;
    uint row = gid / width;
    uint base = row * width * 3;
    query[gid] = qkv[base + column] + q_bias[column];
    key[gid] = qkv[base + width + column] + k_bias[column];
    value[gid] = qkv[base + width * 2 + column] + v_bias[column];

}

__global__ void h3_audio_attention_pool_f32(const float *attended, float *output, audio_pool_args args) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    uint count = args.batch * args.length * args.output_dim;
    if (gid >= count) return;
    uint column = gid % args.output_dim;
    uint row = gid / args.output_dim;
    uint pool = args.head_dim / args.output_dim;
    float sum = 0.0f;
    for (uint head = 0; head < args.heads; head++) {
        uint base = (row * args.heads + head) * args.head_dim + column * pool;
        for (uint item = 0; item < pool; item++) sum += attended[base + item];
    }
    output[gid] = sum / float(args.heads * pool);

}

__global__ void h3_geglu_f32(const float *gate, const float *linear, float *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= count) return;
    float x = gate[gid];
    float cube = x * x * x;
    float gelu = 0.5f * x *
        (1.0f + tanhf(0.7978845608028654f * (x + 0.044715f * cube)));
    output[gid] = gelu * linear[gid];

}

__global__ void h3_clip_f32(const float *input, float *output, clip_args args) {
    uint index = (blockIdx.x*blockDim.x+threadIdx.x);

    if (index < args.elements)
        output[index] = clamp(input[index], args.minimum, args.maximum);

}

__global__ void h3_linear_bf16(const ushort *input, const ushort *weight, const ushort *bias, ushort *output, linear_args args) {
    uint2 tid = make_uint2(threadIdx.x,threadIdx.y);
    uint2 group = make_uint2(blockIdx.x,blockIdx.y);

    /* Adapted from Iris's short-sequence Qwen path. Each 16x16 weight/input
     * tile is loaded once per __shared__ instead of once per output scalar. */
    __shared__ float input_tile[16][16];
    __shared__ float weight_tile[16][16];
    uint row = group.y * 16 + tid.y;
    uint column = group.x * 16 + tid.x;
    float sum = args.has_bias && column < args.output_dim ?
        h3_bf16_to_f32(bias[column]) : 0.0f;
    uint tile_count = (args.input_dim + 15) / 16;
    for (uint tile = 0; tile < tile_count; tile++) {
        uint input_k = tile * 16 + tid.x;
        input_tile[tid.y][tid.x] =
            row < args.rows && input_k < args.input_dim ?
            h3_bf16_to_f32(input[row * args.input_dim + input_k]) : 0.0f;
        uint weight_k = tile * 16 + tid.y;
        weight_tile[tid.y][tid.x] =
            column < args.output_dim && weight_k < args.input_dim ?
            h3_bf16_to_f32(weight[column * args.input_dim + weight_k]) : 0.0f;
        __syncthreads();
        for (uint k = 0; k < 16; k++) {
            sum = fmaf(input_tile[tid.y][k], weight_tile[k][tid.x], sum);
        }
        __syncthreads();
    }
    if (row < args.rows && column < args.output_dim) {
        output[row * args.output_dim + column] = h3_f32_to_bf16(sum);
    }

}

__global__ void h3_silu_bf16(const ushort *input, ushort *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= count) return;
    float value = h3_bf16_to_f32(input[gid]);
    output[gid] = h3_f32_to_bf16(value / (1.0f + expf(-value)));

}

__global__ void h3_rms_norm_bf16(const ushort *input, const ushort *weight, ushort *output, norm_args args) {
    uint3 group = make_uint3(blockIdx.x,blockIdx.y,blockIdx.z);
    uint3 thread_position = make_uint3(threadIdx.x,threadIdx.y,threadIdx.z);
    uint3 threadgroup_size = make_uint3(blockDim.x,blockDim.y,blockDim.z);

    uint row = group.x;
    uint tid = thread_position.x;
    uint threads = threadgroup_size.x;
    if (row >= args.rows) return;
    __shared__ float reductions[256];
    const ushort *x = input + row * args.width;
    float local_sum = 0.0f;
    for (uint k = tid; k < args.width; k += threads) {
        float value = h3_bf16_to_f32(x[k]);
        local_sum = fmaf(value, value, local_sum);
    }
    reductions[tid] = local_sum;
    __syncthreads();
    for (uint stride = threads / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float inverse = rsqrtf(reductions[0] / float(args.width) + args.epsilon);
    for (uint column = tid; column < args.width; column += threads) {
        float normalized = h3_bf16_to_f32(x[column]) * inverse;
        output[row * args.width + column] =
            h3_f32_to_bf16(normalized * h3_bf16_to_f32(weight[column]));
    }

}

__global__ void h3_layer_norm_bf16(const ushort *input, const ushort *weight, const ushort *bias, ushort *output, norm_args args) {
    uint3 group = make_uint3(blockIdx.x,blockIdx.y,blockIdx.z);
    uint3 thread_position = make_uint3(threadIdx.x,threadIdx.y,threadIdx.z);
    uint3 threadgroup_size = make_uint3(blockDim.x,blockDim.y,blockDim.z);

    uint row = group.x;
    uint tid = thread_position.x;
    uint threads = threadgroup_size.x;
    if (row >= args.rows) return;
    __shared__ float reductions[256];
    const ushort *x = input + row * args.width;
    float local_sum = 0.0f;
    for (uint column = tid; column < args.width; column += threads)
        local_sum += h3_bf16_to_f32(x[column]);
    reductions[tid] = local_sum;
    __syncthreads();
    for (uint stride = threads / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float mean = reductions[0] / float(args.width);
    __syncthreads();
    float local_square = 0.0f;
    for (uint column = tid; column < args.width; column += threads) {
        float centered = h3_bf16_to_f32(x[column]) - mean;
        local_square = fmaf(centered, centered, local_square);
    }
    reductions[tid] = local_square;
    __syncthreads();
    for (uint stride = threads / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float inverse = rsqrtf(reductions[0] / float(args.width) + args.epsilon);
    for (uint column = tid; column < args.width; column += threads) {
        float normalized = (h3_bf16_to_f32(x[column]) - mean) * inverse;
        float value = fmaf(normalized, h3_bf16_to_f32(weight[column]),
                          h3_bf16_to_f32(bias[column]));
        output[row * args.width + column] = h3_f32_to_bf16(value);
    }

}

__global__ void h3_gelu_bf16(const ushort *input, ushort *output, gelu_bf16_args args) {
    uint index = (blockIdx.x*blockDim.x+threadIdx.x);

    if (index >= args.elements) return;
    float value = h3_bf16_to_f32(input[index]);
    float activated;
    if (args.approximate) {
        float inner = 0.7978845608028654f *
            (value + 0.044715f * value * value * value);
        /* Apple GPU tanh may return NaN for large finite arguments under the
         * runtime compiler's fast-math mode. Saturation is already exact at
         * BF16 precision outside this range. */
        activated = inner <= -10.0f ? 0.0f :
                    inner >= 10.0f ? value :
                    0.5f * value * (1.0f + tanhf(inner));
    } else {
        activated = value <= -10.0f ? 0.0f :
                    value >= 10.0f ? value :
                    0.5f * value *
                    (1.0f + h3_erf_approx(value * 0.7071067811865475f));
    }
    output[index] = h3_f32_to_bf16(activated);

}

__global__ void h3_vision_qkv_rope_bf16(const ushort *qkv, const ushort *rope_cos, const ushort *rope_sin, ushort *query, ushort *key, ushort *value, qkv_args args) {
    uint3 gid = make_uint3((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y),(blockIdx.z*blockDim.z+threadIdx.z));

    uint dimension = gid.x;
    uint head = gid.y;
    uint row = gid.z;
    if (dimension >= args.head_dim || head >= args.heads ||
        row >= args.sequence) return;
    uint inner = args.heads * args.head_dim;
    uint row_base = row * inner * 3;
    uint q_base = row_base + head * args.head_dim;
    uint k_base = row_base + inner + head * args.head_dim;
    uint v_base = row_base + inner * 2 + head * args.head_dim;
    uint half_dim = args.rope_half;
    uint rope_index = row * half_dim + dimension % half_dim;
    float c = h3_bf16_to_f32(rope_cos[rope_index]);
    float s = h3_bf16_to_f32(rope_sin[rope_index]);
    uint pair = dimension < half_dim ? dimension + half_dim :
                dimension - half_dim;
    float q0 = h3_bf16_to_f32(qkv[q_base + dimension]);
    float k0 = h3_bf16_to_f32(qkv[k_base + dimension]);
    float q1 = h3_bf16_to_f32(qkv[q_base + pair]);
    float k1 = h3_bf16_to_f32(qkv[k_base + pair]);
    float qr = dimension < half_dim ? q0 * c - q1 * s : q0 * c + q1 * s;
    float kr = dimension < half_dim ? k0 * c - k1 * s : k0 * c + k1 * s;
    uint output_index = (row * args.heads + head) * args.head_dim + dimension;
    query[output_index] = h3_f32_to_bf16(qr);
    key[output_index] = h3_f32_to_bf16(kr);
    value[output_index] = qkv[v_base + dimension];

}

__global__ void h3_adaln_bf16(const ushort *input, const ushort *weight, const ushort *modulation, const uint *row_map, ushort *output, adaln_args args) {
    uint3 group = make_uint3(blockIdx.x,blockIdx.y,blockIdx.z);
    uint3 thread_position = make_uint3(threadIdx.x,threadIdx.y,threadIdx.z);
    uint3 threadgroup_size = make_uint3(blockDim.x,blockDim.y,blockDim.z);

    uint row = group.x;
    uint tid = thread_position.x;
    uint threads = threadgroup_size.x;
    if (row >= args.rows) return;
    __shared__ float reductions[256];
    const ushort *x = input + row * args.width;
    float local_sum = 0.0f;
    for (uint k = tid; k < args.width; k += threads) {
        float value = h3_bf16_to_f32(x[k]);
        local_sum = fmaf(value, value, local_sum);
    }
    reductions[tid] = local_sum;
    __syncthreads();
    for (uint stride = threads / 2; stride; stride >>= 1) {
        if (tid < stride) reductions[tid] += reductions[tid + stride];
        __syncthreads();
    }
    float inverse = rsqrtf(reductions[0] / float(args.width) + args.epsilon);
    uint base = row_map[row] * args.slots * args.width;
    for (uint column = tid; column < args.width; column += threads) {
        float normalized = h3_bf16_to_f32(x[column]) * inverse *
            h3_bf16_to_f32(weight[column]);
        float shift = h3_bf16_to_f32(
            modulation[base + args.shift_slot * args.width + column]);
        float scale = h3_bf16_to_f32(
            modulation[base + args.scale_slot * args.width + column]);
        output[row * args.width + column] =
            h3_f32_to_bf16(fmaf(normalized, (1.0f + scale), shift));
    }

}

__global__ void h3_gate_bf16(const ushort *residual, const ushort *branch, const ushort *modulation, const uint *row_map, ushort *output, gate_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    uint base = row_map[row] * args.slots * args.width;
    float gate = h3_bf16_to_f32(modulation[base + args.gate_slot * args.width + column]);
    uint index = row * args.width + column;
    float value = h3_bf16_to_f32(residual[index]) +
                  h3_bf16_to_f32(branch[index]) * gate;
    output[index] = h3_f32_to_bf16(value);

}

__global__ void h3_qkv_rope_bf16(const ushort *qkv, const ushort *q_weight, const ushort *k_weight, const ushort *rope_cos, const ushort *rope_sin, ushort *query, ushort *key, ushort *value, qkv_args args) {
    uint3 gid = make_uint3((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y),(blockIdx.z*blockDim.z+threadIdx.z));

    uint dimension = gid.x;
    uint head = gid.y;
    uint row = gid.z;
    if (dimension >= args.head_dim || head >= args.heads || row >= args.sequence) return;
    uint inner = args.heads * args.head_dim;
    uint row_base = row * inner * 3;
    uint q_base = row_base + head * args.head_dim;
    uint k_base = q_base + inner;
    uint v_base = q_base + inner * 2;
    if (args.grouped) {
        q_base = row_base + head * args.head_dim * 3;
        k_base = q_base + args.head_dim;
        v_base = k_base + args.head_dim;
    }
    float q_sum = 0.0f;
    float k_sum = 0.0f;
    for (uint d = 0; d < args.head_dim; d++) {
        float q = h3_bf16_to_f32(qkv[q_base + d]);
        float k = h3_bf16_to_f32(qkv[k_base + d]);
        q_sum = fmaf(q, q, q_sum);
        k_sum = fmaf(k, k, k_sum);
    }
    float q_inverse = rsqrtf(q_sum / float(args.head_dim) + args.epsilon);
    float k_inverse = rsqrtf(k_sum / float(args.head_dim) + args.epsilon);
    float q0 = h3_bf16_to_f32(qkv[q_base + dimension]) * q_inverse *
               h3_bf16_to_f32(q_weight[dimension]);
    float k0 = h3_bf16_to_f32(qkv[k_base + dimension]) * k_inverse *
               h3_bf16_to_f32(k_weight[dimension]);
    if (dimension < args.rope_half) {
        uint pair = dimension + args.rope_half;
        float q1 = h3_bf16_to_f32(qkv[q_base + pair]) * q_inverse *
                   h3_bf16_to_f32(q_weight[pair]);
        float k1 = h3_bf16_to_f32(qkv[k_base + pair]) * k_inverse *
                   h3_bf16_to_f32(k_weight[pair]);
        float c = h3_bf16_to_f32(rope_cos[row * args.rope_half + dimension]);
        float s = h3_bf16_to_f32(rope_sin[row * args.rope_half + dimension]);
        q0 = q0 * c - q1 * s;
        k0 = k0 * c - k1 * s;
    } else if (dimension < args.rope_half * 2) {
        uint pair = dimension - args.rope_half;
        float q1 = h3_bf16_to_f32(qkv[q_base + pair]) * q_inverse *
                   h3_bf16_to_f32(q_weight[pair]);
        float k1 = h3_bf16_to_f32(qkv[k_base + pair]) * k_inverse *
                   h3_bf16_to_f32(k_weight[pair]);
        float c = h3_bf16_to_f32(rope_cos[row * args.rope_half + pair]);
        float s = h3_bf16_to_f32(rope_sin[row * args.rope_half + pair]);
        q0 = q0 * c + q1 * s;
        k0 = k0 * c + k1 * s;
    }
    uint output_index = (row * args.heads + head) * args.head_dim + dimension;
    query[output_index] = h3_f32_to_bf16(q0);
    key[output_index] = h3_f32_to_bf16(k0);
    value[output_index] = qkv[v_base + dimension];

}

__global__ void h3_swiglu_bf16(const ushort *fused, ushort *output, swiglu_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    uint base = row * args.width * 2;
    float gate = h3_bf16_to_f32(fused[base + column]);
    float up = h3_bf16_to_f32(fused[base + args.width + column]);
    output[row * args.width + column] =
        h3_f32_to_bf16(gate / (1.0f + expf(-gate)) * up);

}

__global__ void h3_embedding_bf16(const ushort *weight, const uint *token_ids, ushort *output, embedding_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint token = gid.y;
    if (token >= args.tokens || column >= args.width) return;
    uint identifier = token_ids[token];
    output[token * args.width + column] = identifier < args.vocab_size ?
        weight[identifier * args.width + column] : ushort(0);

}

__global__ void h3_text_qk_rope_bf16(const ushort *query_input, const ushort *key_input, const ushort *q_weight, const ushort *k_weight, const ushort *rope_cos, const ushort *rope_sin, ushort *query_output, ushort *key_output, text_rope_args args) {
    uint3 gid = make_uint3((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y),(blockIdx.z*blockDim.z+threadIdx.z));

    uint dimension = gid.x;
    uint head = gid.y;
    uint row = gid.z;
    if (dimension >= args.head_dim || head >= args.query_heads || row >= args.sequence) return;
    uint half_dim = args.head_dim / 2;
    uint pair = dimension < half_dim ? dimension + half_dim : dimension - half_dim;
    float c = h3_bf16_to_f32(rope_cos[row * half_dim + (dimension % half_dim)]);
    float s = h3_bf16_to_f32(rope_sin[row * half_dim + (dimension % half_dim)]);

    uint q_base = (row * args.query_heads + head) * args.head_dim;
    float q_sum = 0.0f;
    for (uint d = 0; d < args.head_dim; d++) {
        float value = h3_bf16_to_f32(query_input[q_base + d]);
        q_sum = fmaf(value, value, q_sum);
    }
    float q_inverse = rsqrtf(q_sum / float(args.head_dim) + args.epsilon);
    float q0 = h3_bf16_to_f32(query_input[q_base + dimension]) * q_inverse *
               h3_bf16_to_f32(q_weight[dimension]);
    float q1 = h3_bf16_to_f32(query_input[q_base + pair]) * q_inverse *
               h3_bf16_to_f32(q_weight[pair]);
    float q_rotated = dimension < half_dim ? q0 * c - q1 * s : q0 * c + q1 * s;
    query_output[q_base + dimension] = h3_f32_to_bf16(q_rotated);

    if (head < args.kv_heads) {
        uint k_base = (row * args.kv_heads + head) * args.head_dim;
        float k_sum = 0.0f;
        for (uint d = 0; d < args.head_dim; d++) {
            float value = h3_bf16_to_f32(key_input[k_base + d]);
            k_sum = fmaf(value, value, k_sum);
        }
        float k_inverse = rsqrtf(k_sum / float(args.head_dim) + args.epsilon);
        float k0 = h3_bf16_to_f32(key_input[k_base + dimension]) * k_inverse *
                   h3_bf16_to_f32(k_weight[dimension]);
        float k1 = h3_bf16_to_f32(key_input[k_base + pair]) * k_inverse *
                   h3_bf16_to_f32(k_weight[pair]);
        float k_rotated = dimension < half_dim ? k0 * c - k1 * s : k0 * c + k1 * s;
        key_output[k_base + dimension] = h3_f32_to_bf16(k_rotated);
    }

}

__global__ void h3_head_rms_norm_bf16(ushort *tensor, const ushort *weight, head_norm_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint row = gid.x;
    uint head = gid.y;
    if (row >= args.sequence || head >= args.heads) return;
    uint base = (row * args.heads + head) * args.head_dim;
    float sum = 0.0f;
    for (uint d = 0; d < args.head_dim; d++) {
        float value = h3_bf16_to_f32(tensor[base + d]);
        sum = fmaf(value, value, sum);
    }
    float inverse = rsqrtf(sum / float(args.head_dim) + args.epsilon);
    for (uint d = 0; d < args.head_dim; d++) {
        float value = h3_bf16_to_f32(tensor[base + d]);
        tensor[base + d] = h3_f32_to_bf16(
            value * inverse * h3_bf16_to_f32(weight[d]));
    }

}

__global__ void h3_rope_text_bf16(ushort *query, ushort *key, const float *rope_cos, const float *rope_sin, text_rope_inplace_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint row = gid.x;
    uint head = gid.y;
    if (row >= args.sequence) return;
    uint half_dim = args.head_dim / 2;
    if (head < args.query_heads) {
        uint base = (row * args.query_heads + head) * args.head_dim;
        for (uint d = 0; d < half_dim; d++) {
            float first = h3_bf16_to_f32(query[base + d]);
            float second = h3_bf16_to_f32(query[base + half_dim + d]);
            float c = rope_cos[row * half_dim + d];
            float s = rope_sin[row * half_dim + d];
            query[base + d] = h3_f32_to_bf16(first * c - second * s);
            query[base + half_dim + d] = h3_f32_to_bf16(second * c + first * s);
        }
    }
    if (head < args.kv_heads) {
        uint base = (row * args.kv_heads + head) * args.head_dim;
        for (uint d = 0; d < half_dim; d++) {
            float first = h3_bf16_to_f32(key[base + d]);
            float second = h3_bf16_to_f32(key[base + half_dim + d]);
            float c = rope_cos[row * half_dim + d];
            float s = rope_sin[row * half_dim + d];
            key[base + d] = h3_f32_to_bf16(first * c - second * s);
            key[base + half_dim + d] = h3_f32_to_bf16(second * c + first * s);
        }
    }

}

__global__ void h3_add_bf16(const ushort *left, const ushort *right, ushort *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= count) return;
    output[gid] = h3_f32_to_bf16(h3_bf16_to_f32(left[gid]) +
                                  h3_bf16_to_f32(right[gid]));

}

__global__ void h3_sub_bf16(const ushort *left, const ushort *right, ushort *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= count) return;
    output[gid] = h3_f32_to_bf16(h3_bf16_to_f32(left[gid]) -
                                  h3_bf16_to_f32(right[gid]));

}

__global__ void h3_token_pool_bf16(const ushort *input, const uint2 *pairs, ushort *output, ushort *baseline, const uint *baseline_indices, ushort *original, h3_token_pool_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    uint2 pair = pairs[row];
    ushort first = input[args.input_offset + pair.x * args.width + column];
    original[args.original_offset + pair.x * args.width + column] = first;
    ushort pooled = first;
    if (pair.x != pair.y) {
        ushort second = input[
            args.input_offset + pair.y * args.width + column];
        original[args.original_offset + pair.y * args.width + column] = second;
        float average = (h3_bf16_to_f32(first) +
                         h3_bf16_to_f32(second)) * 0.5f;
        pooled = h3_f32_to_bf16(average);
    }
    output[row * args.width + column] = pooled;
    uint baseline_index = baseline_indices[row];
    if (baseline_index != 0xffffffffu)
        baseline[args.baseline_offset + baseline_index * args.width + column] =
            pooled;

}

__global__ void h3_token_expand_delta_bf16(const ushort *original, const ushort *reduced, const ushort *baseline, const uint *baseline_indices, const uint *parents, ushort *output, h3_token_expand_args args) {
    uint2 gid = make_uint2((blockIdx.x*blockDim.x+threadIdx.x),(blockIdx.y*blockDim.y+threadIdx.y));

    uint column = gid.x;
    uint row = gid.y;
    if (row >= args.rows || column >= args.width) return;
    uint parent = parents[row];
    uint destination = row * args.width + column;
    uint reduced_index = parent * args.width + column;
    if (row < args.exact_prefix_rows) {
        output[destination] = reduced[reduced_index];
    } else {
        uint baseline_row = baseline_indices[parent];
        if (baseline_row == 0xffffffffu) {
            output[destination] = reduced[reduced_index];
            return;
        }
        uint baseline_index = args.baseline_offset +
            baseline_row * args.width + column;
        float update = h3_bf16_to_f32(reduced[reduced_index]) -
                       h3_bf16_to_f32(baseline[baseline_index]);
        output[destination] = h3_f32_to_bf16(
            h3_bf16_to_f32(original[args.original_offset + destination]) +
            args.update_scale * update);
    }

}

__global__ void h3_euler_bf16(float *sample, const ushort *last, const ushort *previous, h3_euler_args args) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= args.elements) return;
    float last_value = h3_bf16_to_f32(last[gid]);
    float velocity = fmaf(args.ratio,
                         last_value - h3_bf16_to_f32(previous[gid]),
                         last_value);
    uint sample_index = args.sample_offset + gid;
    sample[sample_index] = fmaf(args.delta, velocity, sample[sample_index]);

}

__global__ void h3_video_preview_bf16(float *preview, const float *sample, const ushort *last, const ushort *previous, const uint *row_classes, const float *strengths, h3_video_preview_args args) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= args.elements) return;
    uint row = gid / 96, within = gid % 96;
    uint spatial = (args.height / 2) * (args.width / 2);
    uint t = row / spatial, y = (row % spatial) / (args.width / 2) * 2 + (within % 4) / 2;
    uint x = (row % (args.width / 2)) * 2 + within % 2;
    uint output = (((within / 4) * args.time + t) * args.height + y) * args.width + x;
    float state = sample[args.offset + gid];
    // Preserve final/preserved rows bitwise, including signed zero and payloads.
    float mask = 1.0f;
    if (args.masked) {
        uint kind = row_classes[row];
        mask = kind < args.classes ? strengths[kind] : 0.0f;
    }
    if (args.sigma == 0.0f || mask == 0.0f) {
        preview[output] = state;
        return;
    }
    float velocity = h3_bf16_to_f32(last[gid]);
    // Match the corresponding Euler operation order, including its reuse
    // endpoint behavior. Cached BF16 predictions remain untouched.
    if (!args.masked || args.ratio != 0.0f)
        velocity = fmaf(args.ratio, velocity - h3_bf16_to_f32(previous[gid]), velocity);
    if (args.masked) velocity *= mask;
    preview[output] = velocity == 0.0f ? state : fmaf(args.sigma, velocity, state);

}

__global__ void h3_bridge_euler_bf16(float *sample, const ushort *last, const ushort *previous, const uint *row_classes, const float *strengths, h3_bridge_euler_args args) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= args.elements) return;
    uint kind = row_classes[gid / args.row_width];
    if (kind >= args.classes) return; // Exact audit reports invalid classes.
    float mask = strengths[kind];
    if (mask == 0.0f) return; // Do not even load velocity for exact positions.
    float velocity = h3_bf16_to_f32(last[gid]);
    // Fresh evaluations and reuse before a previous prediction use raw last.
    // Preserve that endpoint even when an unused cache contains NaN/Inf.
    if (args.ratio != 0.0f)
        velocity = fmaf(args.ratio,
            velocity - h3_bf16_to_f32(previous[gid]), velocity);
    float scaled = velocity * mask;
    uint index = args.sample_offset + gid;
    sample[index] = fmaf(args.delta, scaled, sample[index]);

}

__global__ void h3_bridge_check_exact(const float *sample, const float *initial, const uint *row_classes, const float *strengths, unsigned *changed, h3_bridge_euler_args args) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= args.elements) return;
    uint kind = row_classes[gid / args.row_width];
    if (kind >= args.classes || !isfinite(strengths[kind]) ||
        strengths[kind] < 0.0f || strengths[kind] > 1.0f) {
        atomicOr(changed, 2u);
    } else if (strengths[kind] == 0.0f &&
        __float_as_uint(sample[args.sample_offset + gid]) !=
        __float_as_uint(initial[gid])) {
        atomicOr(changed, 1u);
    }

}

__global__ void h3_silu_mul_bf16(const ushort *gate, const ushort *up, ushort *output, uint count) {
    uint gid = (blockIdx.x*blockDim.x+threadIdx.x);

    if (gid >= count) return;
    float value = h3_bf16_to_f32(gate[gid]);
    float other = h3_bf16_to_f32(up[gid]);
    output[gid] = h3_f32_to_bf16(value / (1.0f + expf(-value)) * other);

}
