#!/usr/bin/env python3
"""Regenerate the literal CUDA counterparts of portable Metal scalar kernels.

Only explicitly portable kernels are translated; CUDA GEMM, convolution and
online-softmax attention are maintained separately. No runtime shader translation.
"""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
s=(ROOT/'src/metal/shaders.metal').read_text()
def block(text,start):
    a=text.index('{',start); depth=1; i=a+1
    while depth:
        depth+=(text[i]=='{')-(text[i]=='}'); i+=1
    return text[start:i]
skip=('q8','nax','int8','coop','exact_simd','h3_gqa_causal_bf16')
unused={'h3_linear_f32','h3_rms_inverse_bf16','h3_adaln_linear_bf16',
        'h3_gate_adaln_bf16','h3_token_pool_adaln_bf16','h3_token_expand_adaln_bf16'}
kernels={}
for m in re.finditer(r'kernel void (h3_\w+)\(',s):
    if m[1] in unused or any(t in m[1] for t in skip):continue
    kernels[m[1]]=block(s,m.start())
# Structs are plain scalar ABI; retain only definitions referenced by these kernels.
structs={m[1]:m[0] for m in re.finditer(r'struct (\w+)\s*\{[^}]+\};',s)}
used='\n'.join(kernels.values())
structs={n:v for n,v in structs.items() if re.search(r'\b'+n+r'\b',used)}
helpers=[]
for name in ('h3_reflect_coordinate','h3_erf_approx'):
    m=re.search(r'(?:inline float|static int) '+name+r'\(',s)
    helpers.append('__device__ '+block(s,m.start()))
def translate(t):
    t=re.sub(r'\bdevice\s+','',t)
    t=re.sub(r'\bthreadgroup\s+','__shared__ ',t)
    t=t.replace('threadgroup_barrier(mem_flags::mem_threadgroup)','__syncthreads()')
    t=t.replace('as_type<uint>','__float_as_uint').replace('as_type<float>','__uint_as_float')
    t=re.sub(r'\batomic_uint\b','unsigned',t)
    t=re.sub(r'atomic_fetch_or_explicit\(([^,]+), ([^,]+), memory_order_relaxed\)',r'atomicOr(\1, \2)',t)
    for f in ('exp','sin','cos','tanh','sqrt','rsqrt','fma','fabs','pow','floor','ceil'):
        t=re.sub(r'\b'+f+r'\(',f+'f(',t)
    t=re.sub(r'\bfast::','',t)
    # Metal contracts the final AdaLN affine expression. Keep that explicit
    # while disabling accidental contraction in the rest of the CUDA build.
    t=t.replace('normalized * (1.0f + scale) + shift',
                'fmaf(normalized, (1.0f + scale), shift)')
    return t
out=['/* Generated by scripts/cuda_translate_reference.py; edit the generator or\n * authoritative portable Metal kernel, then regenerate. CUDA-specific\n * execution/attention/GEMM remains in separately maintained sources. */',
     'using uint = unsigned int;\nusing ushort = unsigned short;',
     '__device__ inline float h3_bf16_to_f32(ushort v) { return __uint_as_float(uint(v)<<16); }',
     '__device__ inline ushort h3_f32_to_bf16(float v) { uint b=__float_as_uint(v); return ushort((b+0x7fff+((b>>16)&1))>>16); }',
     'template<class T> __device__ T clamp(T v,T lo,T hi) { return min(hi,max(lo,v)); }',
     *structs.values(), *map(translate,helpers)]
metadata={}
for name,k in kernels.items():
    a=k.index('{'); head=k[:a];body=k[a+1:-1]
    params=[]; builtin=[]; meta=[]
    for param in re.split(r',\s*(?![^\[]*\]\])',head[head.index('(')+1:head.rfind(')')]):
        m=re.fullmatch(r'\s*(.*?)\s*\[\[(.*?)\]\]\s*',param,re.S)
        assert m,(name,param)
        decl,attr=m.groups();decl=' '.join(decl.split())
        argname=re.search(r'(\w+)\s*$',decl)[1]
        if attr.startswith('buffer'):
            idx=int(re.search(r'\d+',attr)[0]);
            decl=decl.replace('device ','').replace('constant ','').replace('&','').replace('atomic_uint','unsigned')
            params.append(decl);meta.append((idx,decl,argname))
        else:
            typ=decl.split()[0]
            base={'thread_position_in_grid':'grid','thread_position_in_threadgroup':'threadIdx','threadgroup_position_in_grid':'blockIdx','threads_per_threadgroup':'blockDim'}[attr]
            coords=[f'{base}.{c}' if base!='grid' else f'(blockIdx.{c}*blockDim.{c}+threadIdx.{c})' for c in 'xyz']
            if name == 'h3_alias_free_snake_f32' and base == 'grid':
                # Each launch covers a bounded time range, but filtering must
                # still use global sample coordinates and the full input.
                coords[1] = '(time_base+blockIdx.y*blockDim.y+threadIdx.y)'
            expr=coords[0] if typ=='uint' else 'make_'+typ+'('+','.join(coords[:int(typ[-1])])+')'
            builtin.append(f'    {typ} {argname} = {expr};')
    metadata[name]=meta
    if name == 'h3_alias_free_snake_f32':
        params.append('uint time_base')
    if name == 'h3_qkv_rope_bf16':
        body=body.replace('if (args.grouped & 1)', 'if (args.grouped)')
        body=body.replace('((args.grouped & 2) ? head * args.sequence + row : row * args.heads + head)', '(row * args.heads + head)')
    if name == 'h3_vae_encoder_group_norm_silu_f32':
        body=body.replace('float mean = reductions[0] / float(elements);', 'float mean = reductions[0] / float(elements);\n    __syncthreads();')
    out.append('__global__ void '+name+'('+', '.join(params)+') {\n'+'\n'.join(builtin)+'\n'+translate(body)+'\n}')
(ROOT/'src/cuda/cuda_kernels.cuh').write_text('\n\n'.join(out)+'\n')
# Generate host wrappers only where the Metal function consists of ordinary C
# validation followed by one portable dispatch. Every other API is hand written.
m=(ROOT/'src/metal/gpu.m').read_text();wrappers=[];names=[]
for hit in re.finditer(r'(?:static )?int (h3_gpu_\w+)\(',m):
    fn=block(m,hit.start()); matches=list(re.finditer(r'return h3_gpu_dispatch_(1d|2d|3d|rows|tiled)\(gpu, @"(h3_\w+)",\s*',fn))
    if len(matches)!=1:continue
    d=matches[0]; kind,kernel=d.groups()
    if kernel not in metadata:continue
    lead=fn[:d.start()];tail=fn[d.end():];lambda_at=tail.find('^(id<MTLComputeCommandEncoder> encoder)')
    if lambda_at<0 or '@' in lead.replace('@"','"') or 'NSString' in lead:continue
    dims=tail[:lambda_at].strip().rstrip(',').strip().replace('NSUInteger','size_t');bindings={}
    for b in re.finditer(r'\[encoder setBuffer:TENSOR\((.*?)\)\.buffer\s+offset:(.*?) atIndex:(\d+)\];',tail,re.S):
        bindings[int(b[3])]=('buffer',b[1].strip(),b[2].strip())
    for b in re.finditer(r'\[encoder setBytes:&(\w+) length:sizeof\(\w+\) atIndex:(\d+)\];',tail):
        bindings[int(b[2])]=('value',b[1],'')
    if set(bindings)!={p[0] for p in metadata[kernel]}:continue
    args=[]
    for idx,decl,name in metadata[kernel]:
        typ=decl[:decl.rfind(name)].strip();binding=bindings[idx]
        if binding[0]=='value':args.append(binding[1])
        else:args.append(f'({typ})tensor_pointer({binding[1]}, {binding[2]})')
    lead=lead.replace('H3GPU *gpu = GPU(opaque);','h3_gpu *gpu = opaque;').replace('@"','"')
    lead=re.sub(r'TENSOR\((\w+)\)\.(\w+)',r'\1->\2',lead)
    if 'MTL' in lead or 'GPU(' in lead or '[' in re.sub(r'"[^"\n]*"','',lead):continue
    if kind=='1d':grid=f'dim3(({dims}+255)/256)';threads='dim3(256)'
    elif kind=='rows':grid=f'dim3({dims})';threads='dim3(256)'
    elif kind=='2d':
        xy=dims.split(',');
        if len(xy)!=2:continue
        grid=f'dim3(({xy[0]}+15)/16,({xy[1]}+15)/16)';threads='dim3(16,16)'
    elif kind=='3d':
        xyz=re.fullmatch(r'MTLSizeMake\((.*)\)',dims,re.S)
        if not xyz:continue
        xyz=xyz[1].split(',')
        if len(xyz)!=3:continue
        grid=f'dim3(({xyz[0]}+7)/8,({xyz[1]}+3)/4,({xyz[2]}+3)/4)';threads='dim3(8,4,4)'
    else:continue
    # Struct names occasionally differ between Metal's host and shader code.
    aliases={'euler_args':'h3_euler_args','bridge_euler_args':'h3_bridge_euler_args','video_preview_args':'h3_video_preview_args','token_pool_args':'h3_token_pool_args','token_expand_args':'h3_token_expand_args','token_pool_adaln_args':'h3_token_pool_adaln_args','token_expand_adaln_args':'h3_token_expand_adaln_args','gate_adaln_args':'h3_gate_adaln_args'}
    for a,b in aliases.items():lead=re.sub(r'\b'+a+r'\b',b,lead)
    lead=re.sub(r'typedef struct\s*\{[^}]*\}\s*(?:'+ '|'.join(structs) +r');', '', lead, flags=re.S)
    if kernel=='h3_scale_add_f32':lead=lead.replace('swiglu_args args','scale_add_args args')
    dispatch=f'    {kernel}<<<{grid},{threads},0,gpu->compute>>>('+', '.join(args)+f');\n    return launch_status(gpu, "{kernel}");\n}}'
    if kernel == 'h3_alias_free_snake_f32':
        # CUDA grid.y has at most 65535 blocks. Audio beyond ~8.19 s needs
        # multiple launches with global time offsets, not sliced tensors.
        dispatch='''    constexpr uint32_t time_chunk = 65535u * 4u;
    for (uint64_t time_base = 0; time_base < length; time_base += time_chunk) {
        uint32_t chunk_length = length - (uint32_t)time_base;
        if (chunk_length > time_chunk) chunk_length = time_chunk;
'''+f'        {kernel}<<<dim3((channels+7)/8,(chunk_length+3)/4,(batch+3)/4),{threads},0,gpu->compute>>>('+', '.join(args)+f''', (uint32_t)time_base);
        if (!launch_status(gpu, "{kernel}")) return 0;
    }}
    return 1;
}}'''
    if kernel == 'h3_alias_free_snake_f32':
        reference_dispatch=dispatch.replace('h3_alias_free_snake_f32','h3_sg_alias_free_snake_f32')
        reference_dispatch=reference_dispatch.replace('(uint32_t)time_base);','(uint32_t)time_base, fused);')
        dispatch='''    if(gpu->sglang_audio) {
        // The pinned JIT profiles two static shapes, then one dynamic shape.
        // Calls after that use a dynamic TensorExpr kernel (including FMA).
        if(gpu->sglang_audio_activation_shapes.size()>=8 &&
           !gpu->sglang_audio_activation_shapes.count({batch,length,channels}))
            return h3_gpu_set_error(gpu,"reference audio activation shape limit exceeded");
        bool fused=gpu->sglang_audio_activation_shapes.size()>=3 ||
            gpu->sglang_audio_activation_shapes.count({batch,length,channels});
        gpu->sglang_audio_activation_shapes.emplace(batch,length,channels);
'''+reference_dispatch[:-1]+'    }\n'+dispatch
    if kernel == 'h3_weight_norm_f32':
        dispatch='''    if(gpu->sglang_reference) {
        h3_sg_weight_norm<<<outer,256,0,gpu->compute>>>((const float*)tensor_pointer(vector),
            (const float*)tensor_pointer(magnitude),(float*)tensor_pointer(output),inner);
        return launch_status(gpu,"reference weight norm");
    }
'''+dispatch
    if kernel == 'h3_snake1d_f32':
        dispatch='''    if(gpu->sglang_audio_encoder) {
        h3_sg_snake1d_f32<<<dim3(((uint32_t)count+255)/256),dim3(256),0,gpu->compute>>>(
            (const float*)tensor_pointer(input),(const float*)tensor_pointer(alpha),
            (float*)tensor_pointer(output),args);
        return launch_status(gpu,"reference encoder Snake1d");
    }
'''+dispatch
    if kernel == 'h3_audio_attention_pool_f32':
        dispatch='''    if(gpu->sglang_audio_encoder) {
        if(heads!=8)return h3_gpu_set_error(gpu,"reference audio pooling requires eight heads");
        h3_sg_audio_pool<<<dim3(((uint32_t)output_count+255)/256),256,0,gpu->compute>>>(
            (const float*)tensor_pointer(attended),(float*)tensor_pointer(output),args);
        return launch_status(gpu,"reference audio head mean and adaptive pooling");
    }
'''+dispatch
    if kernel == 'h3_geglu_f32':
        dispatch='''    if(gpu->sglang_audio_encoder) {
        h3_sg_audio_geglu<<<dim3((elements+255)/256),256,0,gpu->compute>>>(
            (const float*)tensor_pointer(gate),(const float*)tensor_pointer(linear),
            (float*)tensor_pointer(output),elements);
        return launch_status(gpu,"reference encoder GeGLU");
    }
'''+dispatch
    # Reference rounding boundaries; retain shared still/operator primitives
    # translated from the authoritative Metal kernels.
    reference_kernels={'h3_adaln_bf16':'h3_sg_adaln_bf16',
                       'h3_rms_norm_bf16':'h3_sg_dit_norm',
                       'h3_gate_bf16':'h3_sg_gate_bf16',
                       'h3_layer_norm_bf16':'h3_sg_vision_layer_norm',
                       'h3_gelu_bf16':'h3_sg_vision_gelu',
                       'h3_swiglu_bf16':'h3_sg_swiglu_bf16'}
    if kernel in reference_kernels:
        ref=reference_kernels[kernel]
        ref_threads='128' if kernel in ('h3_adaln_bf16','h3_rms_norm_bf16','h3_layer_norm_bf16') else threads
        dispatch=(f'    if(gpu->sglang_reference) {{\n        {ref}<<<{grid},{ref_threads},0,gpu->compute>>>('
                  +', '.join(args)+f');\n        return launch_status(gpu, "{ref}");\n    }}\n'+dispatch)
    text_kernels={'h3_rms_norm_bf16':'h3_sg_text_norm',
                  'h3_head_rms_norm_bf16':'h3_sg_text_head_norm',
                  'h3_rope_text_bf16':'h3_sg_text_rope',
                  'h3_silu_mul_bf16':'h3_sg_silu_mul'}
    if kernel in text_kernels:
        ref=text_kernels[kernel]
        ref_grid,ref_threads=(('(sequence*heads+3)/4','128') if kernel=='h3_head_rms_norm_bf16' else (grid,threads))
        if kernel=='h3_rms_norm_bf16':ref_grid,ref_threads='(rows+3)/4','128'
        dispatch=(f'    if(gpu->sglang_text) {{\n        {ref}<<<{ref_grid},{ref_threads},0,gpu->compute>>>('
                  +', '.join(args)+f');\n        return launch_status(gpu, "{ref}");\n    }}\n'+dispatch)
    vae_kernels={'h3_rms_norm_f32':'h3_sg_vae_norm','h3_swiglu_f32':'h3_sg_vae_swiglu',
                 'h3_layer_norm_f32':'h3_sg_vae_layer_norm'}
    if kernel in vae_kernels:
        ref=vae_kernels[kernel]
        ref_threads='128' if kernel in ('h3_rms_norm_f32','h3_layer_norm_f32') else threads
        policy='gpu->sglang_vae || gpu->sglang_audio_encoder' if kernel=='h3_layer_norm_f32' else 'gpu->sglang_vae'
        dispatch=(f'    if({policy}) {{\n        {ref}<<<{grid},{ref_threads},0,gpu->compute>>>('
                  +', '.join(args)+f');\n        return launch_status(gpu, "{ref}");\n    }}\n'+dispatch)
    if kernel=='h3_vision_qkv_rope_bf16':
        start=lead.index('    if (!h3_gpu_require_bf16')
        reference='    if(gpu->sglang_reference) {\n        if(!rope_cos||!rope_sin||rope_cos->dtype!=H3_GPU_F32||rope_sin->dtype!=H3_GPU_F32||\n           !h3_gpu_require_elements(gpu,rope_cos,rope_count,"reference vision cosine")||\n           !h3_gpu_require_elements(gpu,rope_sin,rope_count,"reference vision sine")||\n           !h3_gpu_require_bf16(gpu,qkv,count*3,"reference vision QKV")||\n           !h3_gpu_require_bf16(gpu,query,count,"reference vision Q")||\n           !h3_gpu_require_bf16(gpu,key,count,"reference vision K")||\n           !h3_gpu_require_bf16(gpu,value,count,"reference vision V")||\n           head_dim!=72||rope_half!=36||!launch_ready(gpu))return 0;\n        qkv_args args={sequence,heads,head_dim,rope_half,0,0.f};\n        h3_sg_vision_rope<<<(count+255)/256,256,0,gpu->compute>>>((const ushort*)tensor_pointer(qkv),\n            (const float*)tensor_pointer(rope_cos),(const float*)tensor_pointer(rope_sin),\n            (ushort*)tensor_pointer(query),(ushort*)tensor_pointer(key),(ushort*)tensor_pointer(value),args);\n        return launch_status(gpu,"reference vision RoPE");\n    }\n'
        lead=lead[:start]+reference+lead[start:]
    wrappers.append(lead+'if (!launch_ready(gpu)) return 0;\n    profile_scope timing(gpu,6);\n'+dispatch)
    names.append(hit[1])
(ROOT/'src/cuda/cuda_reference_wrappers.cuh').write_text('/* Generated portable kernel wrappers; see scripts/cuda_translate_reference.py. */\n'+'\n\n'.join(wrappers)+'\n')
print(f'{len(kernels)} portable kernels; {len(names)} wrappers: '+', '.join(names))
