#!/usr/bin/env python3
"""Embed the pinned MIT MLX attention subset, without a runtime MLX dependency."""
from pathlib import Path
import hashlib
import json
import re
import sys

root = Path(__file__).resolve().parents[1]
vendor = root/'third_party/mlx-attention'
manifest = json.loads((vendor/'manifest.json').read_text())
for name, digest in manifest['files'].items():
    if hashlib.sha256((vendor/name).read_bytes()).hexdigest() != digest:
        raise SystemExit('Pinned MLX source differs: '+name)
seen = set()
def expand(name):
    if name in seen:
        return ''
    seen.add(name)
    source = ((root/name) if name.endswith('.metal') else (vendor/name)).read_text().replace('#pragma once', '')
    return '\n// '+name+'\n'+re.sub(r'#include "([^"]+)"', lambda m: expand(m[1]), source)

source = '''#include <metal_stdlib>
using namespace metal;
#ifndef METAL_FUNC
#define METAL_FUNC inline
#endif
template<typename T> struct AccumHelper { using accum_type = float; };
template<typename T> struct Limits;
template<> struct Limits<float> { static constant constexpr float finite_min = -FLT_MAX; };
'''
source += expand('src/metal/native_attention.metal')
source += expand('src/metal/fp16_attention.metal')
source += expand('src/metal/native_diagnostics.metal')
source += expand('src/metal/routed_attention.metal')
source += expand('src/metal/sol.metal')
source += expand('src/upscale/upscale.metal')
for index, (q, k, wm, wn) in enumerate([(32,32,4,1),(32,64,4,1),(64,32,4,2),(16,64,2,1)]):
    source += f'''
template [[host_name("h3_native_attention_{index}")]]
[[kernel]] decltype(attention<bfloat, {q}, {k}, 128, {wm}, {wn}, float, float>)
attention<bfloat, {q}, {k}, 128, {wm}, {wn}, float, float>;
'''
for name, q, k, mode, out, cache in [
        ('candidate_b',32,16,0,'bfloat','true'),
        ('candidate_b64',64,32,0,'bfloat','true'),
        *[(f'sol_{mode}_{q}',q,32,mode,'float','false') for q in (32,64) for mode in (1,2)]]:
    args=f'bfloat, {q}, {k}, 128, 4, {q//32}, float, float, {out}, {mode}, {cache}'
    source += f'''\ntemplate [[host_name("h3_{name}")]] [[kernel]]
decltype(h3_routed_attention<{args}>) h3_routed_attention<{args}>;\n'''
for tile,q,k in [(0,32,16),(1,64,32)]:
    for name,storage,operand,mode in [('half','half','half',1),('recover','bfloat','float',2)]:
        for route in (0,1):
            args=f'{storage}, {q}, {k}, 128, 4, {q//32}, float, float, float, {route}, true, {operand}, {mode}'
            suffix='_sol' if route else ''
            source += f'''\ntemplate [[host_name("h3_fp16_{name}_{tile}{suffix}")]] [[kernel]]
decltype(h3_routed_attention<{args}>) h3_routed_attention<{args}>;\n'''
data = source.encode()+b'\0'
out = '// Generated by scripts/embed_metal_attention.py; see third_party/mlx-attention/LICENSE.\n'
out += 'static const unsigned char h3_native_attention_source[] = {\n'
out += '\n'.join(','.join(str(b) for b in data[i:i+24])+',' for i in range(0,len(data),24))+'\n};\n'
Path(sys.argv[1]).write_text(out)
