#!/usr/bin/env python3
"""Validate and embed the reviewed model catalog; never access the network."""
import argparse
import hashlib
import json
import re
from urllib.parse import urlsplit
from pathlib import Path

GROUPS = {'base': 1, 'references': 2, 'preview': 4, 'image-vae': 8, 'upscale': 16}


def render(source):
    raw = source.read_bytes()
    catalog = json.loads(raw)
    if catalog['schema'] != 1:
        raise ValueError('unsupported model catalog schema')
    rows = []
    seen = set()
    identities = {}
    for item in catalog['artifacts']:
        path = item['path']
        if (not path or path.startswith('/') or '\\' in path or
                any(part in ('', '.', '..') for part in path.split('/')) or path in seen):
            raise ValueError(f'unsafe or duplicate destination: {path}')
        seen.add(path)
        if not re.fullmatch('[a-f0-9]{64}', item['sha256']):
            raise ValueError(f'invalid hash: {path}')
        if not re.fullmatch('[a-f0-9]{40}', item['revision']):
            raise ValueError(f'unpinned revision: {path}')
        if not item['url'].startswith('https://') or item['revision'] not in item['url']:
            raise ValueError(f'unpinned HTTPS URL: {path}')
        if type(item['bytes']) is not int or not 0 < item['bytes'] < 2**63:
            raise ValueError(f'invalid size: {path}')
        previous = identities.setdefault(item['sha256'], item['bytes'])
        if previous != item['bytes']:
            raise ValueError('conflicting shared artifact identity: '+path)
        url = urlsplit(item['url'])
        if url.hostname not in ('huggingface.co','raw.githubusercontent.com') or url.username or url.password or url.port or url.query or url.fragment:
            raise ValueError('unsupported model origin: '+path)
        mask = 0
        for group in item['group'].split(','):
            mask |= GROUPS[group]
        values = ', '.join(json.dumps(item[key]) for key in
                           ('path', 'url', 'sha256', 'repository', 'revision'))
        rows.append(f'    {{{values}, UINT64_C({item["bytes"]}), {mask}u}},')
    digest = hashlib.sha256(raw).hexdigest()
    return ('/* Generated by scripts/embed_model_catalog.py; edit catalog.json. */\n'
            f'const char h3_model_catalog_sha256[] = "{digest}";\n'
            'const h3_model_artifact h3_model_catalog[] = {\n' + '\n'.join(rows) +
            '\n};\nconst size_t h3_model_catalog_count = '
            'sizeof(h3_model_catalog) / sizeof(h3_model_catalog[0]);\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    output = root / 'src/models/catalog.inc'
    content = render(root / 'src/models/catalog.json')
    if args.check:
        if not output.exists() or output.read_text() != content:
            raise SystemExit('embedded model catalog is stale')
    else:
        output.write_text(content)


if __name__ == '__main__':
    main()
